Models/ErrorViewModel.cs
namespace tl2_tp8_2025_jm07_web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Presupuestos.cs
namespace tl2_tp8_2025_jm07_web.Models;

public class Presupuestos
{
    public int IdPresupuesto { get; set; }
    public string? nombreDestinatario { get; set; }
    public string? FechaCreacion { get; set; }
    public List<PresupuestosDetalle> detalle { get; set; }

    public Presupuestos() { }

    public Presupuestos(int id, string nombre, string fecha)
    {
        IdPresupuesto = id;
        nombreDestinatario = nombre;
        FechaCreacion = fecha;
        detalle = new List<PresupuestosDetalle>();
    }

    //Metodos
    public double MontoPresupuesto()
    {
        double monto = 0;
        foreach (var item in detalle)
        {
            monto += item.producto.precio * item.cantidad;
        }
        return monto;
    }

    public double MontoPresupuestoConIva()
    {
        double montoConIVA = 0;
        foreach (var item in detalle)
        {
            montoConIVA += item.producto.precio * item.cantidad;
        }
        return montoConIVA * 1.21;
    }

    public int CantidadProductos()
    {
        int cantidad = 0;
        foreach (var item in detalle)
        {
            cantidad += item.cantidad;
        }
        return cantidad;
    }
}

Models/PresupuestosDetalle.cs
namespace tl2_tp8_2025_jm07_web.Models;

public class PresupuestosDetalle
{
    public Producto producto { get; set; }
    public int cantidad { get; set; }

    public PresupuestosDetalle() { }

    public PresupuestosDetalle(Producto produc, int cant)
    {
        producto = produc;
        cantidad = cant;
    }
}

Models/Productos.cs
namespace tl2_tp8_2025_jm07_web.Models;

public class Producto
{
    public int idProducto { get; set; }
    public string ?descripcion { get; set; }
    public double precio { get; set; }

    public Producto() { }

    public Producto(int id, string descripcion, double precio)
    {
        idProducto = id;
        this.descripcion = descripcion;
        this.precio = precio;
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp8_2025_jm07_web.Models;

namespace tl2_tp8_2025_jm07_web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PresupuestosController.cs
using Microsoft.AspNetCore.Mvc;
using tl2_tp8_2025_jm07_web.Models;
using tl2_tp8_2025_jm07_web.Repositories;

namespace tl2_tp8_2025_jm07_web.Controllers;

public class PresupuestosController : Controller
{
    private PresupuestosRepository presupuestosRepository;
    public PresupuestosController()
    {
        presupuestosRepository = new PresupuestosRepository();
    }
    //A partir de aquí van todos los Action Methods (Get, Post,etc.)

    [HttpGet]
    public IActionResult Index()
    {
        List<Presupuestos> presupuestos = presupuestosRepository.ListarTodosLosPresupuestos();
        return View(presupuestos);
    }

    [HttpGet]
    public IActionResult CrearPresupuesto()
    {
        return View();
    }

    [HttpPost]
    public IActionResult CrearPresupuesto(Presupuestos nuevoPresupuesto)
    {
        presupuestosRepository.CrearPresupuesto(nuevoPresupuesto);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult DetallePresupuesto(int id)
    {
        var presupuesto = presupuestosRepository.ObtenerPorId(id);
        return View(presupuesto);
    }

    [HttpGet]
    public IActionResult ModificarPresupuesto(int id)
    {
        var presupuesto = presupuestosRepository.ObtenerPorId(id);
        return View(presupuesto);
    }

    [HttpPost]
    public IActionResult ModificarPresupuesto(Presupuestos presupuesto)
    {
        presupuestosRepository.ModificarPresupuesto(presupuesto.IdPresupuesto, presupuesto);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult EliminarPresupuesto(int id)
    {
        return View(id);
    }
        
    [HttpGet]
    public IActionResult ConfirmarEliminarPresupuesto(int id)
    {
        if (presupuestosRepository.ObtenerPorId(id) == null) return NotFound();
        presupuestosRepository.EliminarPresupuesto(id);
        return RedirectToAction("Index");     
    }
}

Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using tl2_tp8_2025_jm07_web.Models;
using tl2_tp8_2025_jm07_web.Repositories;

namespace tl2_tp8_2025_jm07_web.Controllers;

public class ProductosController : Controller
{
    private ProductoRepository productoRepository;
    public ProductosController()
    {
        productoRepository = new ProductoRepository();
    }
    //A partir de aquí van todos los Action Methods (Get, Post,etc.)

    [HttpGet]
    public IActionResult Index()
    {
        List<Producto> productos = productoRepository.ListarTodosLosProductos();
        return View(productos);
    }

    [HttpGet]
    public IActionResult CrearProducto()
    {
        return View();
    }

    [HttpPost]
    public IActionResult CrearProducto(Producto nuevoProducto)
    {
        productoRepository.CrearProducto(nuevoProducto);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult ModificarProducto(int id)
    {
        var producto = productoRepository.ObtenerPorId(id);
        return View(producto);
    }

    [HttpPost]
    public IActionResult ModificarProducto(Producto producto)
    {
        productoRepository.ModificarProducto(producto.idProducto, producto);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult EliminarProducto(int id)
    {
        return View(id);
    }
        
    [HttpGet]
    public IActionResult ConfirmarEliminarProducto(int id)
    {
        if (productoRepository.ObtenerPorId(id) == null) return NotFound();
        productoRepository.EliminarProducto(id);
        return RedirectToAction("Index");     
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Presupuestos/CrearPresupuesto.cshtml
@model Presupuestos
<section class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <article class="border rounded p-5">
        <form asp-controller="Presupuestos" asp-action="CrearPresupuesto" method="post">
            <section class="form-group p-2">
                <label asp-for="nombreDestinatario" class="form-label">Nombre del destinatario</label>
                <input type="text" asp-for="nombreDestinatario" class="form-control-sm">
            </section>
            <section class="form-group d-flex justify-content-between p-2">
                <label asp-for="FechaCreacion" class="form-label">Fecha</label>
                <input type="text" asp-for="FechaCreacion" class="form-control-sm">
            </section>
            <section class="form-group p-2">
                <input type="submit" value="crear" class="btn btn-primary">
                <a class="btn btn-secondary" asp-controller="Presupuestos" asp-action="Index">volver</a>
            </section>
        </form>
    </article>
</section>

Views/Presupuestos/DetallePresupuesto.cshtml
@model Presupuestos

<section class="container mt-5">

    <h2 class="mb-4">Detalle del Presupuesto</h2>

    <!-- ENCABEZADO -->
    <section class="card p-3 mb-4">
        <p><strong>ID del Presupuesto:</strong> @Model.IdPresupuesto</p>
        <p><strong>Nombre del destinatario:</strong> @Model.nombreDestinatario</p>
        <p><strong>Fecha de creación:</strong> @Model.FechaCreacion</p>
        <p><strong>Monto Total:</strong> @Model.MontoPresupuesto()</p>
        <p><strong>Monto Total con IVA:</strong> @Model.MontoPresupuestoConIva()</p>
    </section>

    <!-- LISTA DE PRODUCTOS -->
    <h4>Productos incluidos</h4>

    @if (Model.detalle != null && Model.detalle.Count > 0)
    {
        <table class="table table-bordered mt-3 text-center">
            <thead class="table-dark">
                <tr>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.detalle)
                {
                    var subtotal = item.cantidad * item.producto.precio;

                    <tr>
                        <td>@item.producto.descripcion</td>
                        <td>@item.cantidad</td>
                        <td>$@subtotal</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p class="text-muted mt-2">Este presupuesto todavía no tiene productos asociados.</p>
    }
    <a class="btn btn-secondary" asp-controller="Presupuestos" asp-action="Index">volver</a>
</section>

Views/Presupuestos/EliminarPresupuesto.cshtml
@model int
<section class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <article class="border rounded p-5 bg-light">
        <p class="text-center">Confirmar eliminacion</p>
        <section>
            <a asp-controller="Presupuestos" asp-action="ConfirmarEliminarPresupuesto" asp-route-id=@Model class="btn btn-danger m-3">Confirmar</a>
            <a asp-controller="Presupuestos" asp-action="Index" class="btn btn-primary m-3">Cancelar</a>
        </section>
    </article>
</section>

Views/Presupuestos/Index.cshtml
using tl2_tp8_2025_jm07_web.Models;
@model List<Presupuestos>

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1 justify-content-center">
                <li class="nav-item">
                    <a class="btn btn-primary" asp-controller="Presupuestos" asp-action="CrearPresupuesto">Crear Presupuesto</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<h2 class="text-center">LISTADO DE PRESUPUESTOS</h2>
<section>
    <article>
        <table class="table table-bordered bordered-info text-center">
            <thead class="table-dark">
            <th>Nombre del Destinatario</th>
            <th>Fecha</th>
            <th colspan="3">Acciones</th>
            </thead>
            <tbody>
                @{
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.nombreDestinatario</td>
                            <td>@item.FechaCreacion</td>

                            <td><a asp-controller="Presupuestos" asp-action="DetallePresupuesto" asp-route-id="@item.IdPresupuesto" class="btn btn-secondary">Detalle</a></td>
                            <td><a asp-controller="Presupuestos" asp-action="ModificarPresupuesto" asp-route-id="@item.IdPresupuesto" class="btn btn-secondary">Modificar</a></td>
                            <td><a asp-controller="Presupuestos" asp-action="EliminarPresupuesto" asp-route-id="@item.IdPresupuesto" class="btn btn-danger">Eliminar</a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </article>
</section>

Views/Presupuestos/ModificarPresupuesto.cshtml
@model Presupuestos
<section class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <article class="border rounded p-5">
        <form asp-controller="Presupuestos" asp-action="ModificarPresupuesto" method="post">
            <section class="form-group p-2">
                <label asp-for="nombreDestinatario" class="form-label">Nombre del Destinatario</label>
                <input type="text" asp-for="nombreDestinatario" class="form-control-sm" value="@Model.nombreDestinatario">
            </section>
            <section class="form-group d-flex justify-content-between p-2">
                <label asp-for="FechaCreacion" class="form-label">Fecha</label>
                <input type="text" asp-for="FechaCreacion" class="form-control-sm" value="@Model.FechaCreacion">
            </section>
            <input type="hidden" asp-for="@Model.IdPresupuesto">
            <section class="form-group p-2">
                <input type="submit" value="modificar" class="btn btn-primary">
                <a class="btn btn-danger " asp-controller="Presupuestos" asp-action="Index">volver</a>
            </section>
        </form>
    </article>
</section>

Views/Productos/CrearProducto.cshtml
@model Producto
<section class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <article class="border rounded p-5">
        <form asp-controller="Productos" asp-action="CrearProducto" method="post">
            <section class="form-group p-2">
                <label asp-for="descripcion" class="form-label">Descripcion</label>
                <input type="text" asp-for="descripcion" class="form-control-sm">
            </section>
            <section class="form-group d-flex justify-content-between p-2">
                <label asp-for="precio" class="form-label">Precio</label>
                <input type="number" asp-for="precio" class="form-control-sm">
            </section>
            <section class="form-group p-2">
                <input type="submit" value="crear" class="btn btn-primary">
                <a class="btn btn-danger " asp-controller="Productos" asp-action="Index">volver</a>
            </section>
        </form>
    </article>
</section>

Views/Productos/EliminarProducto.cshtml
@model int
<section class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <article class="border rounded p-5 bg-light">
        <p class="text-center">Confirmar eliminacion</p>
        <section>
            <a asp-controller="Productos" asp-action="ConfirmarEliminarProducto" asp-route-id=@Model class="btn btn-danger m-3">Confirmar</a>
            <a asp-controller="Productos" asp-action="Index" class="btn btn-primary m-3">Cancelar</a>
        </section>
    </article>
</section>

Views/Productos/Index.cshtml
using tl2_tp8_2025_jm07_web.Models;
@model List<Producto>

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1 justify-content-center">
                <li class="nav-item">
                    <a class="btn btn-primary" asp-controller="Productos" asp-action="CrearProducto">Crear Producto</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<h2 class="text-center">LISTADO DE PRODUCTOS</h2>
<section>
    <article>
        <table class="table table-bordered bordered-info text-center">
            <thead class="text-center table-dark">
            <th>Descripcion</th>
            <th>Precio</th>
            <th colspan="2">Acciones</th>
            </thead>
            @{
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.descripcion</td>
                        <td>@item.precio</td>

                        <td><a asp-controller="Productos" asp-action="ModificarProducto" asp-route-id="@item.idProducto" class="btn btn-secondary">Modificar</a></td>
                        <td><a asp-controller="Productos" asp-action="EliminarProducto" asp-route-id="@item.idProducto" class="btn btn-danger">Eliminar</a></td>
                    </tr>
                }
            }
        </table>
    </article>
</section>

Views/Productos/ModificarProducto.cshtml
@model Producto
<section class="d-flex justify-content-center align-items-center" style="height: 70vh;">
    <article class="border rounded p-5">
        <form asp-controller="Productos" asp-action="ModificarProducto" method="post">
            <section class="form-group p-2">
                <label asp-for="descripcion" class="form-label">Descripcion</label>
                <input type="text" asp-for="descripcion" class="form-control-sm" value="@Model.descripcion">
            </section>
            <section class="form-group d-flex justify-content-between p-2">
                <label asp-for="precio" class="form-label">Precio</label>
                <input type="number" asp-for="precio" class="form-control-sm" value="@Model.precio">
            </section>
            <input type="hidden" asp-for="@Model.idProducto">
            <section class="form-group p-2">
                <input type="submit" value="modificar" class="btn btn-primary">
                <a class="btn btn-secondary" asp-controller="Productos" asp-action="Index">volver</a>
            </section>
        </form>
    </article>
</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tl2_tp8_2025_jm07_web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tl2_tp8_2025_jm07_web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tl2_tp8_2025_jm07_web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Presupuestos" asp-action="Index">Presupuestos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - tl2_tp8_2025_jm07_web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>